config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- https://www.ea.com/ -->
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@glidejs/glide/dist/css/glide.core.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@glidejs/glide/dist/css/glide.theme.min.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous" defer></script>
  </head>

  <body>
    <div class = 'container'>
      <div class = 'row'>
        <div class = 'col-12'>
          <svg class="svg-icon float-end" viewBox="-950 -10 1000 30">
            <path d="M12.075,10.812c1.358-0.853,2.242-2.507,2.242-4.037c0-2.181-1.795-4.618-4.198-4.618S5.921,4.594,5.921,6.775c0,1.53,0.884,3.185,2.242,4.037c-3.222,0.865-5.6,3.807-5.6,7.298c0,0.23,0.189,0.42,0.42,0.42h14.273c0.23,0,0.42-0.189,0.42-0.42C17.676,14.619,15.297,11.677,12.075,10.812 M6.761,6.775c0-2.162,1.773-3.778,3.358-3.778s3.359,1.616,3.359,3.778c0,2.162-1.774,3.778-3.359,3.778S6.761,8.937,6.761,6.775 M3.415,17.69c0.218-3.51,3.142-6.297,6.704-6.297c3.562,0,6.486,2.787,6.705,6.297H3.415z"></path>
          </svg>
        </div>
        <div class = 'col-12'>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <a class="btn btn-dark me-2" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                  More
                </a>
                <a class="navbar-brand" href="#"><h4>Primitive Artlessness</h4></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Main
                      </a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "Home", pages_home_path, class: "dropdown-item"%></li>
                        <li><%= link_to "Contact", pages_contact_path, class: "dropdown-item"%></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                      </ul>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        More Experiences
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                      </ul>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        About
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                      </ul>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                      </ul>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                      </ul>
                    </li>
                  </ul>
                </div>
            </nav>
            <hr>
        </div>
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title text-center" id="offcanvasExampleLabel">Weekly Photos</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <div class = 'row'>
              <div class = 'col-12'>
                <img src="https://dummyimage.com/400x300/000/fff" class="img-thumbnail rounded bg-black" alt="...">
              </div>
              <div class = 'col-6'>
                <img src="https://dummyimage.com/150x150/000/fff" class="img-thumbnail rounded bg-black" alt="...">
              </div>
              <div class = 'col-6'>
                <img src="https://dummyimage.com/150x150/000/fff" class="img-thumbnail rounded bg-black" alt="...">
              </div>
              <div class = 'col-6'>
                <img src="https://dummyimage.com/150x150/000/fff" class="img-thumbnail rounded bg-black" alt="...">
              </div>
              <div class = 'col-6'>
                <img src="https://dummyimage.com/150x150/000/fff" class="img-thumbnail rounded bg-black" alt="...">
              </div>
              <div class = 'col-6'>
                <img src="https://dummyimage.com/150x150/000/fff" class="img-thumbnail rounded bg-black" alt="...">
              </div>
              <div class = 'col-6'>
                <img src="https://dummyimage.com/150x150/000/fff" class="img-thumbnail rounded bg-black" alt="...">
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="position-relative text-center">
        <div class="glide">
          <div class="glide__track" data-glide-el="track">
            <ul class="glide__slides">
              <li class="glide__slide"><img src="https://dummyimage.com/1300x300/ffffff/fff&text=+" class="img-thumbnail rounded bg-black" alt="..."></li>
              <li class="glide__slide"><img src="https://dummyimage.com/1300x300/ffffff/fff&text=+" class="img-thumbnail rounded bg-black" alt="..."></li>
              <li class="glide__slide"><img src="https://dummyimage.com/1300x300/ffffff/fff&text=+" class="img-thumbnail rounded bg-black" alt="..."></li>
            </ul>
          </div>
          <div class="glide__arrows" data-glide-el="controls">
            <button class="glide__arrow glide__arrow--left bg-black" data-glide-dir="<">prev</button>
            <button class="glide__arrow glide__arrow--right bg-black" data-glide-dir=">">next</button>
          </div>
        </div>
        <div class="position-absolute top-50 start-50 translate-middle overlay">
          <h1 class="fw-bold text-center text-dark">Gio's Epic Website</h1>
        </div>
      </div>
      
      <%= yield %>

      <script src="https://cdn.jsdelivr.net/npm/@glidejs/glide"></script>
      <script>
        new Glide('.glide', {
          type: 'carousel',
          startAt: 0,
          perView: 1,
          animationDuration: 800,
          keyboard: true,
        }).mount()
      </script>
      <div class="navbar navbar-default navbar-fixed-bottom">
        <form>
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Description</label>
              <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class = 'row'>
  <div class = 'col-12'>
  </div>
  <div class = 'col-12'>
  </div>
  <div class = 'col-12'>
  </div>
  <div class = 'col-12'>
  </div>
  <div class = 'col-12'>
  </div>
  <div class = 'col-12'>
  </div>
  <div class = 'col-12'>
  </div>
  <div class = 'col-12'>
  </div>
</div>